# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AppDataBase\AppDataBaseUI\TasksWindowsUI\TasksDeleteWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TasksDeleteWindow(object):
    def setupUi(self, TasksDeleteWindow):
        TasksDeleteWindow.setObjectName("TasksDeleteWindow")
        TasksDeleteWindow.resize(880, 320)
        TasksDeleteWindow.setMinimumSize(QtCore.QSize(880, 320))
        TasksDeleteWindow.setMaximumSize(QtCore.QSize(880, 320))
        self.DeleteTaskGroupBox = QtWidgets.QGroupBox(TasksDeleteWindow)
        self.DeleteTaskGroupBox.setGeometry(QtCore.QRect(20, 10, 840, 290))
        self.DeleteTaskGroupBox.setObjectName("DeleteTaskGroupBox")
        self.EventsGroupBox = QtWidgets.QGroupBox(self.DeleteTaskGroupBox)
        self.EventsGroupBox.setGeometry(QtCore.QRect(20, 20, 500, 210))
        self.EventsGroupBox.setObjectName("EventsGroupBox")
        self.EventsTableView = QtWidgets.QTableView(self.EventsGroupBox)
        self.EventsTableView.setGeometry(QtCore.QRect(10, 20, 480, 180))
        self.EventsTableView.setObjectName("EventsTableView")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.DeleteTaskGroupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 240, 800, 40))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.HorizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.HorizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.HorizontalLayout.setObjectName("HorizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.HorizontalLayout.addItem(spacerItem)
        self.DeleteTaskButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.DeleteTaskButton.setObjectName("DeleteTaskButton")
        self.HorizontalLayout.addWidget(self.DeleteTaskButton)
        self.CancelButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.CancelButton.setObjectName("CancelButton")
        self.HorizontalLayout.addWidget(self.CancelButton)
        self.TasksForTheEventGroupBox = QtWidgets.QGroupBox(self.DeleteTaskGroupBox)
        self.TasksForTheEventGroupBox.setGeometry(QtCore.QRect(530, 20, 290, 210))
        self.TasksForTheEventGroupBox.setObjectName("TasksForTheEventGroupBox")
        self.TasksForTheEventTableView = QtWidgets.QTableView(self.TasksForTheEventGroupBox)
        self.TasksForTheEventTableView.setGeometry(QtCore.QRect(10, 20, 270, 180))
        self.TasksForTheEventTableView.setObjectName("TasksForTheEventTableView")

        self.retranslateUi(TasksDeleteWindow)
        QtCore.QMetaObject.connectSlotsByName(TasksDeleteWindow)

    def retranslateUi(self, TasksDeleteWindow):
        _translate = QtCore.QCoreApplication.translate
        TasksDeleteWindow.setWindowTitle(_translate("TasksDeleteWindow", "Dialog"))
        self.DeleteTaskGroupBox.setTitle(_translate("TasksDeleteWindow", "Delete Task"))
        self.EventsGroupBox.setTitle(_translate("TasksDeleteWindow", "Events"))
        self.DeleteTaskButton.setText(_translate("TasksDeleteWindow", "Delete Task"))
        self.CancelButton.setText(_translate("TasksDeleteWindow", "Cancel"))
        self.TasksForTheEventGroupBox.setTitle(_translate("TasksDeleteWindow", "Tasks For The Event "))
