# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AppDataBase\AppDataBaseUI\TasksWindowsUI\TasksWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TasksWindow(object):
    def setupUi(self, TasksWindow):
        TasksWindow.setObjectName("TasksWindow")
        TasksWindow.resize(720, 480)
        TasksWindow.setMinimumSize(QtCore.QSize(720, 480))
        TasksWindow.setMaximumSize(QtCore.QSize(720, 480))
        self.TasksFunctionsBox = QtWidgets.QGroupBox(TasksWindow)
        self.TasksFunctionsBox.setGeometry(QtCore.QRect(20, 10, 680, 450))
        self.TasksFunctionsBox.setObjectName("TasksFunctionsBox")
        self.CreateTaskBox = QtWidgets.QGroupBox(self.TasksFunctionsBox)
        self.CreateTaskBox.setGeometry(QtCore.QRect(20, 20, 120, 80))
        self.CreateTaskBox.setObjectName("CreateTaskBox")
        self.CreateTaskButton = QtWidgets.QPushButton(self.CreateTaskBox)
        self.CreateTaskButton.setGeometry(QtCore.QRect(10, 20, 100, 50))
        self.CreateTaskButton.setObjectName("CreateTaskButton")
        self.UpdateTaskBox = QtWidgets.QGroupBox(self.TasksFunctionsBox)
        self.UpdateTaskBox.setGeometry(QtCore.QRect(20, 110, 120, 80))
        self.UpdateTaskBox.setObjectName("UpdateTaskBox")
        self.UpdateTaskButton = QtWidgets.QPushButton(self.UpdateTaskBox)
        self.UpdateTaskButton.setGeometry(QtCore.QRect(10, 20, 100, 50))
        self.UpdateTaskButton.setObjectName("UpdateTaskButton")
        self.DeleteTaskBox = QtWidgets.QGroupBox(self.TasksFunctionsBox)
        self.DeleteTaskBox.setGeometry(QtCore.QRect(20, 200, 120, 80))
        self.DeleteTaskBox.setObjectName("DeleteTaskBox")
        self.DeleteTaskButton = QtWidgets.QPushButton(self.DeleteTaskBox)
        self.DeleteTaskButton.setGeometry(QtCore.QRect(10, 20, 100, 50))
        self.DeleteTaskButton.setObjectName("DeleteTaskButton")
        self.EventsBox = QtWidgets.QGroupBox(self.TasksFunctionsBox)
        self.EventsBox.setGeometry(QtCore.QRect(150, 20, 510, 170))
        self.EventsBox.setObjectName("EventsBox")
        self.EventsTableView = QtWidgets.QTableView(self.EventsBox)
        self.EventsTableView.setGeometry(QtCore.QRect(10, 20, 490, 140))
        self.EventsTableView.setObjectName("EventsTableView")
        self.TasksForTheEventBox = QtWidgets.QGroupBox(self.TasksFunctionsBox)
        self.TasksForTheEventBox.setGeometry(QtCore.QRect(150, 200, 510, 170))
        self.TasksForTheEventBox.setObjectName("TasksForTheEventBox")
        self.TasksForTheEventTableView = QtWidgets.QTableView(self.TasksForTheEventBox)
        self.TasksForTheEventTableView.setGeometry(QtCore.QRect(10, 20, 490, 140))
        self.TasksForTheEventTableView.setObjectName("TasksForTheEventTableView")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.TasksFunctionsBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 380, 641, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.HorizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.HorizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.HorizontalLayout.setObjectName("HorizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.HorizontalLayout.addItem(spacerItem)
        self.CancelButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.CancelButton.setObjectName("CancelButton")
        self.HorizontalLayout.addWidget(self.CancelButton)

        self.retranslateUi(TasksWindow)
        QtCore.QMetaObject.connectSlotsByName(TasksWindow)

    def retranslateUi(self, TasksWindow):
        _translate = QtCore.QCoreApplication.translate
        TasksWindow.setWindowTitle(_translate("TasksWindow", "Dialog"))
        self.TasksFunctionsBox.setTitle(_translate("TasksWindow", "Tasks Functions"))
        self.CreateTaskBox.setTitle(_translate("TasksWindow", "Create Task"))
        self.CreateTaskButton.setText(_translate("TasksWindow", "Create Task"))
        self.UpdateTaskBox.setTitle(_translate("TasksWindow", "Update Task"))
        self.UpdateTaskButton.setText(_translate("TasksWindow", "Update Task"))
        self.DeleteTaskBox.setTitle(_translate("TasksWindow", "Delete Task"))
        self.DeleteTaskButton.setText(_translate("TasksWindow", "Delete Task"))
        self.EventsBox.setTitle(_translate("TasksWindow", "Events"))
        self.TasksForTheEventBox.setTitle(_translate("TasksWindow", "Tasks for the Event"))
        self.CancelButton.setText(_translate("TasksWindow", "Cancel"))
