# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AppDataBase\AppDataBaseUI\EventsWindowsUI\EventsUpdateWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EventsUpdateWindow(object):
    def setupUi(self, EventsUpdateWindow):
        EventsUpdateWindow.setObjectName("EventsUpdateWindow")
        EventsUpdateWindow.resize(800, 330)
        EventsUpdateWindow.setMinimumSize(QtCore.QSize(800, 330))
        EventsUpdateWindow.setMaximumSize(QtCore.QSize(800, 330))
        self.EventUpdateBox = QtWidgets.QGroupBox(EventsUpdateWindow)
        self.EventUpdateBox.setGeometry(QtCore.QRect(10, 10, 780, 310))
        self.EventUpdateBox.setObjectName("EventUpdateBox")
        self.TitleBox = QtWidgets.QGroupBox(self.EventUpdateBox)
        self.TitleBox.setGeometry(QtCore.QRect(20, 20, 120, 50))
        self.TitleBox.setObjectName("TitleBox")
        self.TitlePlainTextEdit = QtWidgets.QPlainTextEdit(self.TitleBox)
        self.TitlePlainTextEdit.setGeometry(QtCore.QRect(10, 20, 100, 20))
        self.TitlePlainTextEdit.setObjectName("TitlePlainTextEdit")
        self.DescriptionBox = QtWidgets.QGroupBox(self.EventUpdateBox)
        self.DescriptionBox.setGeometry(QtCore.QRect(150, 20, 260, 230))
        self.DescriptionBox.setObjectName("DescriptionBox")
        self.DescriptionPlainTextEdit = QtWidgets.QPlainTextEdit(self.DescriptionBox)
        self.DescriptionPlainTextEdit.setGeometry(QtCore.QRect(10, 20, 240, 200))
        self.DescriptionPlainTextEdit.setObjectName("DescriptionPlainTextEdit")
        self.EventDateBox = QtWidgets.QGroupBox(self.EventUpdateBox)
        self.EventDateBox.setGeometry(QtCore.QRect(20, 80, 120, 50))
        self.EventDateBox.setObjectName("EventDateBox")
        self.EventDateEdit = QtWidgets.QDateEdit(self.EventDateBox)
        self.EventDateEdit.setGeometry(QtCore.QRect(10, 20, 100, 20))
        self.EventDateEdit.setObjectName("EventDateEdit")
        self.StartTimeBox = QtWidgets.QGroupBox(self.EventUpdateBox)
        self.StartTimeBox.setGeometry(QtCore.QRect(20, 140, 120, 50))
        self.StartTimeBox.setObjectName("StartTimeBox")
        self.StartTimeEdit = QtWidgets.QTimeEdit(self.StartTimeBox)
        self.StartTimeEdit.setGeometry(QtCore.QRect(10, 20, 100, 20))
        self.StartTimeEdit.setObjectName("StartTimeEdit")
        self.EndTimeBox = QtWidgets.QGroupBox(self.EventUpdateBox)
        self.EndTimeBox.setGeometry(QtCore.QRect(20, 200, 120, 50))
        self.EndTimeBox.setObjectName("EndTimeBox")
        self.EndTimeEdit = QtWidgets.QTimeEdit(self.EndTimeBox)
        self.EndTimeEdit.setGeometry(QtCore.QRect(10, 20, 100, 20))
        self.EndTimeEdit.setObjectName("EndTimeEdit")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.EventUpdateBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 260, 740, 40))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.HorizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.HorizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.HorizontalLayout.setObjectName("HorizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.HorizontalLayout.addItem(spacerItem)
        self.UpdateEventButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.UpdateEventButton.setObjectName("UpdateEventButton")
        self.HorizontalLayout.addWidget(self.UpdateEventButton)
        self.CancelButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.CancelButton.setObjectName("CancelButton")
        self.HorizontalLayout.addWidget(self.CancelButton)
        self.EventsBox = QtWidgets.QGroupBox(self.EventUpdateBox)
        self.EventsBox.setGeometry(QtCore.QRect(420, 20, 340, 230))
        self.EventsBox.setObjectName("EventsBox")
        self.EventsTableView = QtWidgets.QTableView(self.EventsBox)
        self.EventsTableView.setGeometry(QtCore.QRect(10, 20, 320, 200))
        self.EventsTableView.setObjectName("EventsTableView")

        self.retranslateUi(EventsUpdateWindow)
        QtCore.QMetaObject.connectSlotsByName(EventsUpdateWindow)

    def retranslateUi(self, EventsUpdateWindow):
        _translate = QtCore.QCoreApplication.translate
        EventsUpdateWindow.setWindowTitle(_translate("EventsUpdateWindow", "Dialog"))
        self.EventUpdateBox.setTitle(_translate("EventsUpdateWindow", "Update Event"))
        self.TitleBox.setTitle(_translate("EventsUpdateWindow", "Title"))
        self.DescriptionBox.setTitle(_translate("EventsUpdateWindow", "Description"))
        self.EventDateBox.setTitle(_translate("EventsUpdateWindow", "Event Date"))
        self.StartTimeBox.setTitle(_translate("EventsUpdateWindow", "Start Time"))
        self.EndTimeBox.setTitle(_translate("EventsUpdateWindow", "End Time"))
        self.UpdateEventButton.setText(_translate("EventsUpdateWindow", "Update Event"))
        self.CancelButton.setText(_translate("EventsUpdateWindow", "Cancel"))
        self.EventsBox.setTitle(_translate("EventsUpdateWindow", "Events"))
