# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AppDataBase\AppDataBaseUI\EventsWindowsUI\EventsDeleteWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EventsDeleteWindow(object):
    def setupUi(self, EventsDeleteWindow):
        EventsDeleteWindow.setObjectName("EventsDeleteWindow")
        EventsDeleteWindow.resize(450, 330)
        EventsDeleteWindow.setMinimumSize(QtCore.QSize(450, 330))
        EventsDeleteWindow.setMaximumSize(QtCore.QSize(450, 330))
        self.EventDeleteBox = QtWidgets.QGroupBox(EventsDeleteWindow)
        self.EventDeleteBox.setGeometry(QtCore.QRect(10, 10, 430, 310))
        self.EventDeleteBox.setObjectName("EventDeleteBox")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.EventDeleteBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 260, 390, 40))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.HorizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.HorizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.HorizontalLayout.setObjectName("HorizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.HorizontalLayout.addItem(spacerItem)
        self.EventDeleteButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.EventDeleteButton.setObjectName("EventDeleteButton")
        self.HorizontalLayout.addWidget(self.EventDeleteButton)
        self.CancelButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.CancelButton.setObjectName("CancelButton")
        self.HorizontalLayout.addWidget(self.CancelButton)
        self.EventsBox = QtWidgets.QGroupBox(self.EventDeleteBox)
        self.EventsBox.setGeometry(QtCore.QRect(20, 20, 390, 230))
        self.EventsBox.setObjectName("EventsBox")
        self.EventsTableView = QtWidgets.QTableView(self.EventsBox)
        self.EventsTableView.setGeometry(QtCore.QRect(10, 20, 370, 200))
        self.EventsTableView.setObjectName("EventsTableView")

        self.retranslateUi(EventsDeleteWindow)
        QtCore.QMetaObject.connectSlotsByName(EventsDeleteWindow)

    def retranslateUi(self, EventsDeleteWindow):
        _translate = QtCore.QCoreApplication.translate
        EventsDeleteWindow.setWindowTitle(_translate("EventsDeleteWindow", "Dialog"))
        self.EventDeleteBox.setTitle(_translate("EventsDeleteWindow", "Delete Event"))
        self.EventDeleteButton.setText(_translate("EventsDeleteWindow", "Delete Event"))
        self.CancelButton.setText(_translate("EventsDeleteWindow", "Cancel"))
        self.EventsBox.setTitle(_translate("EventsDeleteWindow", "Events"))
