# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AppDataBase\AppDataBaseUI\EventsWindowsUI\EventsWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EventsWindow(object):
    def setupUi(self, EventsWindow):
        EventsWindow.setObjectName("EventsWindow")
        EventsWindow.resize(630, 370)
        EventsWindow.setMinimumSize(QtCore.QSize(630, 370))
        EventsWindow.setMaximumSize(QtCore.QSize(630, 370))
        self.EventsFunctionsBox = QtWidgets.QGroupBox(EventsWindow)
        self.EventsFunctionsBox.setGeometry(QtCore.QRect(20, 20, 590, 340))
        self.EventsFunctionsBox.setObjectName("EventsFunctionsBox")
        self.CreateEventBox = QtWidgets.QGroupBox(self.EventsFunctionsBox)
        self.CreateEventBox.setGeometry(QtCore.QRect(20, 20, 120, 80))
        self.CreateEventBox.setObjectName("CreateEventBox")
        self.CreateEventButton = QtWidgets.QPushButton(self.CreateEventBox)
        self.CreateEventButton.setGeometry(QtCore.QRect(10, 20, 100, 50))
        self.CreateEventButton.setObjectName("CreateEventButton")
        self.DeleteEventBox = QtWidgets.QGroupBox(self.EventsFunctionsBox)
        self.DeleteEventBox.setGeometry(QtCore.QRect(20, 200, 120, 80))
        self.DeleteEventBox.setObjectName("DeleteEventBox")
        self.DeleteEventButton = QtWidgets.QPushButton(self.DeleteEventBox)
        self.DeleteEventButton.setGeometry(QtCore.QRect(10, 20, 100, 50))
        self.DeleteEventButton.setObjectName("DeleteEventButton")
        self.UpdateEventBox = QtWidgets.QGroupBox(self.EventsFunctionsBox)
        self.UpdateEventBox.setGeometry(QtCore.QRect(20, 110, 120, 80))
        self.UpdateEventBox.setObjectName("UpdateEventBox")
        self.UpdateEventButton = QtWidgets.QPushButton(self.UpdateEventBox)
        self.UpdateEventButton.setGeometry(QtCore.QRect(10, 20, 100, 50))
        self.UpdateEventButton.setObjectName("UpdateEventButton")
        self.ViewingEventsBox = QtWidgets.QGroupBox(self.EventsFunctionsBox)
        self.ViewingEventsBox.setGeometry(QtCore.QRect(150, 20, 420, 260))
        self.ViewingEventsBox.setObjectName("ViewingEventsBox")
        self.ViewingEventsTableView = QtWidgets.QTableView(self.ViewingEventsBox)
        self.ViewingEventsTableView.setGeometry(QtCore.QRect(10, 20, 400, 230))
        self.ViewingEventsTableView.setObjectName("ViewingEventsTableView")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.EventsFunctionsBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 290, 550, 40))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.HorizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.HorizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.HorizontalLayout.setObjectName("HorizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.HorizontalLayout.addItem(spacerItem)
        self.UpdateTheTableButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.UpdateTheTableButton.setObjectName("UpdateTheTableButton")
        self.HorizontalLayout.addWidget(self.UpdateTheTableButton)
        self.CancelButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.CancelButton.setObjectName("CancelButton")
        self.HorizontalLayout.addWidget(self.CancelButton)

        self.retranslateUi(EventsWindow)
        QtCore.QMetaObject.connectSlotsByName(EventsWindow)

    def retranslateUi(self, EventsWindow):
        _translate = QtCore.QCoreApplication.translate
        EventsWindow.setWindowTitle(_translate("EventsWindow", "Dialog"))
        self.EventsFunctionsBox.setTitle(_translate("EventsWindow", "Events Functions"))
        self.CreateEventBox.setTitle(_translate("EventsWindow", "Create Event"))
        self.CreateEventButton.setText(_translate("EventsWindow", "Create Event"))
        self.DeleteEventBox.setTitle(_translate("EventsWindow", "Delete Event"))
        self.DeleteEventButton.setText(_translate("EventsWindow", "Delete Event"))
        self.UpdateEventBox.setTitle(_translate("EventsWindow", "Update Event"))
        self.UpdateEventButton.setText(_translate("EventsWindow", "Update Event"))
        self.ViewingEventsBox.setTitle(_translate("EventsWindow", "Viewing Events"))
        self.UpdateTheTableButton.setText(_translate("EventsWindow", "Update the table"))
        self.CancelButton.setText(_translate("EventsWindow", "Cancel"))
