# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AppDataBase\AppDataBaseUI\ContactsWindowsUI\ContactsCreateWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ContactsCreateWindow(object):
    def setupUi(self, ContactsCreateWindow):
        ContactsCreateWindow.setObjectName("ContactsCreateWindow")
        ContactsCreateWindow.resize(610, 480)
        ContactsCreateWindow.setMinimumSize(QtCore.QSize(610, 480))
        ContactsCreateWindow.setMaximumSize(QtCore.QSize(610, 480))
        self.CreateContactBox = QtWidgets.QGroupBox(ContactsCreateWindow)
        self.CreateContactBox.setGeometry(QtCore.QRect(20, 20, 570, 440))
        self.CreateContactBox.setObjectName("CreateContactBox")
        self.FullNameBox = QtWidgets.QGroupBox(self.CreateContactBox)
        self.FullNameBox.setGeometry(QtCore.QRect(20, 20, 200, 80))
        self.FullNameBox.setObjectName("FullNameBox")
        self.FullNamePlainTextEdit = QtWidgets.QPlainTextEdit(self.FullNameBox)
        self.FullNamePlainTextEdit.setGeometry(QtCore.QRect(10, 20, 180, 50))
        self.FullNamePlainTextEdit.setObjectName("FullNamePlainTextEdit")
        self.PhoneBox = QtWidgets.QGroupBox(self.CreateContactBox)
        self.PhoneBox.setGeometry(QtCore.QRect(20, 110, 200, 80))
        self.PhoneBox.setObjectName("PhoneBox")
        self.PhonePlainTextEdit = QtWidgets.QPlainTextEdit(self.PhoneBox)
        self.PhonePlainTextEdit.setGeometry(QtCore.QRect(10, 20, 180, 50))
        self.PhonePlainTextEdit.setObjectName("PhonePlainTextEdit")
        self.EmailBox = QtWidgets.QGroupBox(self.CreateContactBox)
        self.EmailBox.setGeometry(QtCore.QRect(20, 200, 200, 80))
        self.EmailBox.setObjectName("EmailBox")
        self.EmailPlainTextEdit = QtWidgets.QPlainTextEdit(self.EmailBox)
        self.EmailPlainTextEdit.setGeometry(QtCore.QRect(10, 20, 180, 50))
        self.EmailPlainTextEdit.setObjectName("EmailPlainTextEdit")
        self.AddressBox = QtWidgets.QGroupBox(self.CreateContactBox)
        self.AddressBox.setGeometry(QtCore.QRect(20, 290, 200, 80))
        self.AddressBox.setObjectName("AddressBox")
        self.AddressPlainTextEdit = QtWidgets.QPlainTextEdit(self.AddressBox)
        self.AddressPlainTextEdit.setGeometry(QtCore.QRect(10, 20, 180, 50))
        self.AddressPlainTextEdit.setObjectName("AddressPlainTextEdit")
        self.EventsBox = QtWidgets.QGroupBox(self.CreateContactBox)
        self.EventsBox.setGeometry(QtCore.QRect(230, 20, 320, 350))
        self.EventsBox.setObjectName("EventsBox")
        self.EventsTableView = QtWidgets.QTableView(self.EventsBox)
        self.EventsTableView.setGeometry(QtCore.QRect(10, 20, 300, 320))
        self.EventsTableView.setObjectName("EventsTableView")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.CreateContactBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 380, 530, 40))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.HorizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.HorizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.HorizontalLayout.setObjectName("HorizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.HorizontalLayout.addItem(spacerItem)
        self.CreateContactButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.CreateContactButton.setObjectName("CreateContactButton")
        self.HorizontalLayout.addWidget(self.CreateContactButton)
        self.CancelButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.CancelButton.setObjectName("CancelButton")
        self.HorizontalLayout.addWidget(self.CancelButton)

        self.retranslateUi(ContactsCreateWindow)
        QtCore.QMetaObject.connectSlotsByName(ContactsCreateWindow)

    def retranslateUi(self, ContactsCreateWindow):
        _translate = QtCore.QCoreApplication.translate
        ContactsCreateWindow.setWindowTitle(_translate("ContactsCreateWindow", "Dialog"))
        self.CreateContactBox.setTitle(_translate("ContactsCreateWindow", "Create Contact"))
        self.FullNameBox.setTitle(_translate("ContactsCreateWindow", "Full Name"))
        self.PhoneBox.setTitle(_translate("ContactsCreateWindow", "Phone"))
        self.EmailBox.setTitle(_translate("ContactsCreateWindow", "Email"))
        self.AddressBox.setTitle(_translate("ContactsCreateWindow", "Address"))
        self.EventsBox.setTitle(_translate("ContactsCreateWindow", "Events"))
        self.CreateContactButton.setText(_translate("ContactsCreateWindow", "Create Contact"))
        self.CancelButton.setText(_translate("ContactsCreateWindow", "Cancel"))
