# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AppDataBase\AppDataBaseUI\ContactsWindowsUI\ContactsDeleteWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ContactsDeleteWindow(object):
    def setupUi(self, ContactsDeleteWindow):
        ContactsDeleteWindow.setObjectName("ContactsDeleteWindow")
        ContactsDeleteWindow.resize(690, 360)
        ContactsDeleteWindow.setMinimumSize(QtCore.QSize(690, 360))
        ContactsDeleteWindow.setMaximumSize(QtCore.QSize(690, 360))
        self.DeleteContactBox = QtWidgets.QGroupBox(ContactsDeleteWindow)
        self.DeleteContactBox.setGeometry(QtCore.QRect(20, 20, 650, 320))
        self.DeleteContactBox.setObjectName("DeleteContactBox")
        self.EventsBox = QtWidgets.QGroupBox(self.DeleteContactBox)
        self.EventsBox.setGeometry(QtCore.QRect(20, 20, 300, 230))
        self.EventsBox.setObjectName("EventsBox")
        self.EventsTableView = QtWidgets.QTableView(self.EventsBox)
        self.EventsTableView.setGeometry(QtCore.QRect(10, 20, 280, 200))
        self.EventsTableView.setObjectName("EventsTableView")
        self.ContactsForTheEventBox = QtWidgets.QGroupBox(self.DeleteContactBox)
        self.ContactsForTheEventBox.setGeometry(QtCore.QRect(330, 20, 300, 230))
        self.ContactsForTheEventBox.setObjectName("ContactsForTheEventBox")
        self.ContactsForTheEventTableView = QtWidgets.QTableView(self.ContactsForTheEventBox)
        self.ContactsForTheEventTableView.setGeometry(QtCore.QRect(10, 20, 280, 200))
        self.ContactsForTheEventTableView.setObjectName("ContactsForTheEventTableView")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.DeleteContactBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 260, 610, 40))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.HorizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.HorizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.HorizontalLayout.setObjectName("HorizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.HorizontalLayout.addItem(spacerItem)
        self.DeleteContactButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.DeleteContactButton.setObjectName("DeleteContactButton")
        self.HorizontalLayout.addWidget(self.DeleteContactButton)
        self.CancelButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.CancelButton.setObjectName("CancelButton")
        self.HorizontalLayout.addWidget(self.CancelButton)

        self.retranslateUi(ContactsDeleteWindow)
        QtCore.QMetaObject.connectSlotsByName(ContactsDeleteWindow)

    def retranslateUi(self, ContactsDeleteWindow):
        _translate = QtCore.QCoreApplication.translate
        ContactsDeleteWindow.setWindowTitle(_translate("ContactsDeleteWindow", "Dialog"))
        self.DeleteContactBox.setTitle(_translate("ContactsDeleteWindow", "Delete Contact"))
        self.EventsBox.setTitle(_translate("ContactsDeleteWindow", "Events"))
        self.ContactsForTheEventBox.setTitle(_translate("ContactsDeleteWindow", "Contacts For The Event"))
        self.DeleteContactButton.setText(_translate("ContactsDeleteWindow", "Delete Contact"))
        self.CancelButton.setText(_translate("ContactsDeleteWindow", "Cancel"))
