# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AppDataBase\AppDataBaseUI\ContactsWindowsUI\ContactsUpdateWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ContactsUpdateWindow(object):
    def setupUi(self, ContactsUpdateWindow):
        ContactsUpdateWindow.setObjectName("ContactsUpdateWindow")
        ContactsUpdateWindow.resize(900, 480)
        ContactsUpdateWindow.setMinimumSize(QtCore.QSize(900, 480))
        ContactsUpdateWindow.setMaximumSize(QtCore.QSize(900, 480))
        self.UpdateContactBox = QtWidgets.QGroupBox(ContactsUpdateWindow)
        self.UpdateContactBox.setGeometry(QtCore.QRect(20, 20, 860, 440))
        self.UpdateContactBox.setObjectName("UpdateContactBox")
        self.FullNameBox = QtWidgets.QGroupBox(self.UpdateContactBox)
        self.FullNameBox.setGeometry(QtCore.QRect(20, 20, 200, 80))
        self.FullNameBox.setObjectName("FullNameBox")
        self.FullNamePlainTextEdit = QtWidgets.QPlainTextEdit(self.FullNameBox)
        self.FullNamePlainTextEdit.setGeometry(QtCore.QRect(10, 20, 180, 50))
        self.FullNamePlainTextEdit.setObjectName("FullNamePlainTextEdit")
        self.PhoneBox = QtWidgets.QGroupBox(self.UpdateContactBox)
        self.PhoneBox.setGeometry(QtCore.QRect(20, 110, 200, 80))
        self.PhoneBox.setObjectName("PhoneBox")
        self.PhonePlainTextEdit = QtWidgets.QPlainTextEdit(self.PhoneBox)
        self.PhonePlainTextEdit.setGeometry(QtCore.QRect(10, 20, 180, 50))
        self.PhonePlainTextEdit.setObjectName("PhonePlainTextEdit")
        self.EmailBox = QtWidgets.QGroupBox(self.UpdateContactBox)
        self.EmailBox.setGeometry(QtCore.QRect(20, 200, 200, 80))
        self.EmailBox.setObjectName("EmailBox")
        self.EmailPlainTextEdit = QtWidgets.QPlainTextEdit(self.EmailBox)
        self.EmailPlainTextEdit.setGeometry(QtCore.QRect(10, 20, 180, 50))
        self.EmailPlainTextEdit.setObjectName("EmailPlainTextEdit")
        self.AddressBox = QtWidgets.QGroupBox(self.UpdateContactBox)
        self.AddressBox.setGeometry(QtCore.QRect(20, 290, 200, 80))
        self.AddressBox.setObjectName("AddressBox")
        self.AddressPlainTextEdit = QtWidgets.QPlainTextEdit(self.AddressBox)
        self.AddressPlainTextEdit.setGeometry(QtCore.QRect(10, 20, 180, 50))
        self.AddressPlainTextEdit.setObjectName("AddressPlainTextEdit")
        self.EventsBox = QtWidgets.QGroupBox(self.UpdateContactBox)
        self.EventsBox.setGeometry(QtCore.QRect(230, 20, 300, 350))
        self.EventsBox.setObjectName("EventsBox")
        self.EventsTableView = QtWidgets.QTableView(self.EventsBox)
        self.EventsTableView.setGeometry(QtCore.QRect(10, 20, 280, 320))
        self.EventsTableView.setObjectName("EventsTableView")
        self.ContactsForTheEventsBox = QtWidgets.QGroupBox(self.UpdateContactBox)
        self.ContactsForTheEventsBox.setGeometry(QtCore.QRect(540, 20, 300, 350))
        self.ContactsForTheEventsBox.setObjectName("ContactsForTheEventsBox")
        self.ContactsForTheEventsTableView = QtWidgets.QTableView(self.ContactsForTheEventsBox)
        self.ContactsForTheEventsTableView.setGeometry(QtCore.QRect(10, 20, 280, 320))
        self.ContactsForTheEventsTableView.setObjectName("ContactsForTheEventsTableView")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.UpdateContactBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 380, 820, 40))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.HorizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.HorizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.HorizontalLayout.setObjectName("HorizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.HorizontalLayout.addItem(spacerItem)
        self.UpdateContactButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.UpdateContactButton.setObjectName("UpdateContactButton")
        self.HorizontalLayout.addWidget(self.UpdateContactButton)
        self.CancelButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.CancelButton.setObjectName("CancelButton")
        self.HorizontalLayout.addWidget(self.CancelButton)

        self.retranslateUi(ContactsUpdateWindow)
        QtCore.QMetaObject.connectSlotsByName(ContactsUpdateWindow)

    def retranslateUi(self, ContactsUpdateWindow):
        _translate = QtCore.QCoreApplication.translate
        ContactsUpdateWindow.setWindowTitle(_translate("ContactsUpdateWindow", "Dialog"))
        self.UpdateContactBox.setTitle(_translate("ContactsUpdateWindow", "Update Contact"))
        self.FullNameBox.setTitle(_translate("ContactsUpdateWindow", "Full Name"))
        self.PhoneBox.setTitle(_translate("ContactsUpdateWindow", "Phone"))
        self.EmailBox.setTitle(_translate("ContactsUpdateWindow", "Email"))
        self.AddressBox.setTitle(_translate("ContactsUpdateWindow", "Address"))
        self.EventsBox.setTitle(_translate("ContactsUpdateWindow", "Events"))
        self.ContactsForTheEventsBox.setTitle(_translate("ContactsUpdateWindow", "Contacts For The Events"))
        self.UpdateContactButton.setText(_translate("ContactsUpdateWindow", "UpdateContact"))
        self.CancelButton.setText(_translate("ContactsUpdateWindow", "Cancel"))
