# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AppDataBase\AppDataBaseUI\NotesWindowsUI\NotesDeleteWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NotesDeleteWindow(object):
    def setupUi(self, NotesDeleteWindow):
        NotesDeleteWindow.setObjectName("NotesDeleteWindow")
        NotesDeleteWindow.resize(710, 360)
        NotesDeleteWindow.setMinimumSize(QtCore.QSize(710, 360))
        NotesDeleteWindow.setMaximumSize(QtCore.QSize(710, 360))
        self.DeleteNote = QtWidgets.QGroupBox(NotesDeleteWindow)
        self.DeleteNote.setGeometry(QtCore.QRect(20, 20, 670, 320))
        self.DeleteNote.setObjectName("DeleteNote")
        self.TasksBox = QtWidgets.QGroupBox(self.DeleteNote)
        self.TasksBox.setGeometry(QtCore.QRect(20, 30, 310, 220))
        self.TasksBox.setObjectName("TasksBox")
        self.TasksTableView = QtWidgets.QTableView(self.TasksBox)
        self.TasksTableView.setGeometry(QtCore.QRect(10, 20, 290, 190))
        self.TasksTableView.setObjectName("TasksTableView")
        self.NotesForTheTaskBox = QtWidgets.QGroupBox(self.DeleteNote)
        self.NotesForTheTaskBox.setGeometry(QtCore.QRect(340, 30, 310, 220))
        self.NotesForTheTaskBox.setObjectName("NotesForTheTaskBox")
        self.NotesForTheTaskTableView = QtWidgets.QTableView(self.NotesForTheTaskBox)
        self.NotesForTheTaskTableView.setGeometry(QtCore.QRect(10, 20, 290, 190))
        self.NotesForTheTaskTableView.setObjectName("NotesForTheTaskTableView")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.DeleteNote)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 260, 630, 40))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.HorizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.HorizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.HorizontalLayout.setObjectName("HorizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.HorizontalLayout.addItem(spacerItem)
        self.DeleteNoteButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.DeleteNoteButton.setObjectName("DeleteNoteButton")
        self.HorizontalLayout.addWidget(self.DeleteNoteButton)
        self.CancelButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.CancelButton.setObjectName("CancelButton")
        self.HorizontalLayout.addWidget(self.CancelButton)

        self.retranslateUi(NotesDeleteWindow)
        QtCore.QMetaObject.connectSlotsByName(NotesDeleteWindow)

    def retranslateUi(self, NotesDeleteWindow):
        _translate = QtCore.QCoreApplication.translate
        NotesDeleteWindow.setWindowTitle(_translate("NotesDeleteWindow", "Dialog"))
        self.DeleteNote.setTitle(_translate("NotesDeleteWindow", "Delete Note"))
        self.TasksBox.setTitle(_translate("NotesDeleteWindow", "Tasks"))
        self.NotesForTheTaskBox.setTitle(_translate("NotesDeleteWindow", "Notes For The Task"))
        self.DeleteNoteButton.setText(_translate("NotesDeleteWindow", "Delete Note"))
        self.CancelButton.setText(_translate("NotesDeleteWindow", "Cancel"))
