# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AppDataBase\AppDataBaseUI\NotesWindowsUI\NotesWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NotesWindow(object):
    def setupUi(self, NotesWindow):
        NotesWindow.setObjectName("NotesWindow")
        NotesWindow.resize(600, 470)
        NotesWindow.setMinimumSize(QtCore.QSize(600, 470))
        NotesWindow.setMaximumSize(QtCore.QSize(600, 470))
        self.NotesFunctionsBox = QtWidgets.QGroupBox(NotesWindow)
        self.NotesFunctionsBox.setGeometry(QtCore.QRect(20, 10, 560, 440))
        self.NotesFunctionsBox.setObjectName("NotesFunctionsBox")
        self.CreateNoteBox = QtWidgets.QGroupBox(self.NotesFunctionsBox)
        self.CreateNoteBox.setGeometry(QtCore.QRect(20, 20, 120, 80))
        self.CreateNoteBox.setObjectName("CreateNoteBox")
        self.CreateNoteButton = QtWidgets.QPushButton(self.CreateNoteBox)
        self.CreateNoteButton.setGeometry(QtCore.QRect(10, 20, 100, 50))
        self.CreateNoteButton.setObjectName("CreateNoteButton")
        self.UpdateNoteBox = QtWidgets.QGroupBox(self.NotesFunctionsBox)
        self.UpdateNoteBox.setGeometry(QtCore.QRect(20, 110, 120, 80))
        self.UpdateNoteBox.setObjectName("UpdateNoteBox")
        self.UpdateNoteButton = QtWidgets.QPushButton(self.UpdateNoteBox)
        self.UpdateNoteButton.setGeometry(QtCore.QRect(10, 20, 100, 50))
        self.UpdateNoteButton.setObjectName("UpdateNoteButton")
        self.DeleteNoteBox = QtWidgets.QGroupBox(self.NotesFunctionsBox)
        self.DeleteNoteBox.setGeometry(QtCore.QRect(20, 200, 120, 80))
        self.DeleteNoteBox.setObjectName("DeleteNoteBox")
        self.DeleteNoteButton = QtWidgets.QPushButton(self.DeleteNoteBox)
        self.DeleteNoteButton.setGeometry(QtCore.QRect(10, 20, 100, 50))
        self.DeleteNoteButton.setObjectName("DeleteNoteButton")
        self.TasksBox = QtWidgets.QGroupBox(self.NotesFunctionsBox)
        self.TasksBox.setGeometry(QtCore.QRect(150, 20, 390, 170))
        self.TasksBox.setObjectName("TasksBox")
        self.TasksTableView = QtWidgets.QTableView(self.TasksBox)
        self.TasksTableView.setGeometry(QtCore.QRect(10, 20, 370, 140))
        self.TasksTableView.setObjectName("TasksTableView")
        self.NotesForTheTaskBox = QtWidgets.QGroupBox(self.NotesFunctionsBox)
        self.NotesForTheTaskBox.setGeometry(QtCore.QRect(150, 200, 390, 170))
        self.NotesForTheTaskBox.setObjectName("NotesForTheTaskBox")
        self.NotesForTheTaskTableView = QtWidgets.QTableView(self.NotesForTheTaskBox)
        self.NotesForTheTaskTableView.setGeometry(QtCore.QRect(10, 20, 370, 140))
        self.NotesForTheTaskTableView.setObjectName("NotesForTheTaskTableView")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.NotesFunctionsBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 380, 520, 40))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.HorizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.HorizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.HorizontalLayout.setObjectName("HorizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.HorizontalLayout.addItem(spacerItem)
        self.CancelButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.CancelButton.setObjectName("CancelButton")
        self.HorizontalLayout.addWidget(self.CancelButton)

        self.retranslateUi(NotesWindow)
        QtCore.QMetaObject.connectSlotsByName(NotesWindow)

    def retranslateUi(self, NotesWindow):
        _translate = QtCore.QCoreApplication.translate
        NotesWindow.setWindowTitle(_translate("NotesWindow", "Dialog"))
        self.NotesFunctionsBox.setTitle(_translate("NotesWindow", "Notes Functions"))
        self.CreateNoteBox.setTitle(_translate("NotesWindow", "Create Note"))
        self.CreateNoteButton.setText(_translate("NotesWindow", "Create Note"))
        self.UpdateNoteBox.setTitle(_translate("NotesWindow", "Update Note"))
        self.UpdateNoteButton.setText(_translate("NotesWindow", "Update Note"))
        self.DeleteNoteBox.setTitle(_translate("NotesWindow", "Delete Note"))
        self.DeleteNoteButton.setText(_translate("NotesWindow", "Delete Note"))
        self.TasksBox.setTitle(_translate("NotesWindow", "Tasks"))
        self.NotesForTheTaskBox.setTitle(_translate("NotesWindow", "Notes For The Tasks"))
        self.CancelButton.setText(_translate("NotesWindow", "Cancel"))
