# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AppDataBase\AppDataBaseUI\NotesWindowsUI\NotesUpdateWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NotesUpdateWindow(object):
    def setupUi(self, NotesUpdateWindow):
        NotesUpdateWindow.setObjectName("NotesUpdateWindow")
        NotesUpdateWindow.resize(840, 390)
        NotesUpdateWindow.setMinimumSize(QtCore.QSize(840, 390))
        NotesUpdateWindow.setMaximumSize(QtCore.QSize(840, 390))
        self.UpdateNoteBox = QtWidgets.QGroupBox(NotesUpdateWindow)
        self.UpdateNoteBox.setGeometry(QtCore.QRect(20, 20, 800, 350))
        self.UpdateNoteBox.setObjectName("UpdateNoteBox")
        self.TitleBox = QtWidgets.QGroupBox(self.UpdateNoteBox)
        self.TitleBox.setGeometry(QtCore.QRect(20, 20, 120, 80))
        self.TitleBox.setObjectName("TitleBox")
        self.TitlePlainTextEdit = QtWidgets.QPlainTextEdit(self.TitleBox)
        self.TitlePlainTextEdit.setGeometry(QtCore.QRect(10, 20, 100, 50))
        self.TitlePlainTextEdit.setObjectName("TitlePlainTextEdit")
        self.ContentBox = QtWidgets.QGroupBox(self.UpdateNoteBox)
        self.ContentBox.setGeometry(QtCore.QRect(20, 110, 120, 110))
        self.ContentBox.setObjectName("ContentBox")
        self.ContentPlainTextEdit = QtWidgets.QPlainTextEdit(self.ContentBox)
        self.ContentPlainTextEdit.setGeometry(QtCore.QRect(10, 20, 100, 80))
        self.ContentPlainTextEdit.setObjectName("ContentPlainTextEdit")
        self.CreatedDateBox = QtWidgets.QGroupBox(self.UpdateNoteBox)
        self.CreatedDateBox.setGeometry(QtCore.QRect(20, 230, 120, 50))
        self.CreatedDateBox.setObjectName("CreatedDateBox")
        self.CreatedDateEdit = QtWidgets.QDateEdit(self.CreatedDateBox)
        self.CreatedDateEdit.setGeometry(QtCore.QRect(10, 20, 100, 20))
        self.CreatedDateEdit.setObjectName("CreatedDateEdit")
        self.TasksBox = QtWidgets.QGroupBox(self.UpdateNoteBox)
        self.TasksBox.setGeometry(QtCore.QRect(150, 20, 310, 260))
        self.TasksBox.setObjectName("TasksBox")
        self.TasksTableView = QtWidgets.QTableView(self.TasksBox)
        self.TasksTableView.setGeometry(QtCore.QRect(10, 20, 290, 230))
        self.TasksTableView.setObjectName("TasksTableView")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.UpdateNoteBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 290, 760, 40))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.HorizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.HorizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.HorizontalLayout.setObjectName("HorizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.HorizontalLayout.addItem(spacerItem)
        self.UpdateNoteButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.UpdateNoteButton.setObjectName("UpdateNoteButton")
        self.HorizontalLayout.addWidget(self.UpdateNoteButton)
        self.CancelButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.CancelButton.setObjectName("CancelButton")
        self.HorizontalLayout.addWidget(self.CancelButton)
        self.NotesForTheTaskBox = QtWidgets.QGroupBox(self.UpdateNoteBox)
        self.NotesForTheTaskBox.setGeometry(QtCore.QRect(470, 20, 310, 260))
        self.NotesForTheTaskBox.setObjectName("NotesForTheTaskBox")
        self.NotesForTheTaskTableView = QtWidgets.QTableView(self.NotesForTheTaskBox)
        self.NotesForTheTaskTableView.setGeometry(QtCore.QRect(10, 20, 290, 230))
        self.NotesForTheTaskTableView.setObjectName("NotesForTheTaskTableView")

        self.retranslateUi(NotesUpdateWindow)
        QtCore.QMetaObject.connectSlotsByName(NotesUpdateWindow)

    def retranslateUi(self, NotesUpdateWindow):
        _translate = QtCore.QCoreApplication.translate
        NotesUpdateWindow.setWindowTitle(_translate("NotesUpdateWindow", "Dialog"))
        self.UpdateNoteBox.setTitle(_translate("NotesUpdateWindow", "Update Note"))
        self.TitleBox.setTitle(_translate("NotesUpdateWindow", "Title"))
        self.ContentBox.setTitle(_translate("NotesUpdateWindow", "Content"))
        self.CreatedDateBox.setTitle(_translate("NotesUpdateWindow", "Created Date"))
        self.TasksBox.setTitle(_translate("NotesUpdateWindow", "Tasks"))
        self.UpdateNoteButton.setText(_translate("NotesUpdateWindow", "Update Note"))
        self.CancelButton.setText(_translate("NotesUpdateWindow", "Cancel"))
        self.NotesForTheTaskBox.setTitle(_translate("NotesUpdateWindow", "Notes For The Task"))
